spring:
  application:
    name: eureka-discovery-server
server:
  port: ${EUREKA_SERVER_PORT:8761}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true