spring:
  application:
    name: eureka-discovery-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true

server:
  port: ${SERVER_PORT_EUREKA}

management:
  endpoints:
    web:
      exposure:
        include: health